//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::categories::Entity as Categories;
pub use super::products::Entity as Products;
pub use super::users::Entity as Users;
pub use super::variants::Entity as Variants;
